### ISSUE TITLE
Not able to install this plugin.

### ISSUE THREAD

**Issue by ForkedInTime** [TypistTech/vagrant-sudo-rsync#9]
E:\vagrantbro>vagrant plugin install vagrant-sudo-rsync
Installing the 'vagrant-sudo-rsync' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

vagrant-sudo-rsync requires Ruby version < 2.4, ~> 2.2.

E:\vagrantbro>ruby --version
ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]

E:\vagrantbro> ?

**Comment by ForkedInTime** [comment]
Not entirely sure if it's Bundler or the actual plugin. Please advise.

**Comment by tangrufus** [comment]
That is beacuse v0.1.0 restricted Ruby version to 2.2.x and 2.3.x.
This requirement was lifted on 16 Sep 2017, but I never tagged a new release.

I just tagged v0.1.1. Please try again.
However, I rarely use vagrant nowadays. You might want to use other similar vagrant plugins.

**Comment by ForkedInTime** [comment]
what do you use instead of vagrant? Docker? I am just trying to move files from my VM to local (using vagrant it doesn't work).

E:\vagrantbro
λ vagrant plugin install vagrant-sudo-rsync
Installing the 'vagrant-sudo-rsync' plugin. This can take a few minutes...
Fetching: vagrant-sudo-rsync-0.1.1.gem (100%)
Installed the plugin 'vagrant-sudo-rsync (0.1.1)'!

Thanks!

**Comment by tangrufus** [comment]
> what do you use instead of vagrant? 

Docker, [valet](https://laravel.com/docs/5.7/valet)
sometimes I just let my rails apps pollute my laptop
